jdk:
  - oraclejdk8

script:
  - mvn clean install && mvn -Prun-its clean integration-test
  
after_success:
- coveralls

deploy:
  skip_cleanup: true
  provider: script
  script: ./scripts/release.sh

